# Generated by Django 5.1.6 on 2025-03-08 19:32

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the bootstrap icon",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.CreateModel(
            name="PartnerIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title when this page appears on listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text description used when this page appears on listings. It's also used if meta description is absent",
                        max_length=255,
                    ),
                ),
                (
                    "appear_in_search_results",
                    models.BooleanField(
                        default=True,
                        help_text="Make this page indexable by search engines.If unchecked this page will no longer be indexed by search engines.",
                    ),
                ),
                (
                    "intro",
                    models.TextField(blank=True, help_text="Text to describe the page"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Landscape mode only; horizontal width between 1000px to 3000px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose an image you wish to be displayed when this page appears on listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose an image you wish to display when this page appears on social media",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "partnerindexpage",
                "verbose_name_plural": "partnerindexpages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="PartnerPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title when this page appears on listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text description used when this page appears on listings. It's also used if meta description is absent",
                        max_length=255,
                    ),
                ),
                (
                    "appear_in_search_results",
                    models.BooleanField(
                        default=True,
                        help_text="Make this page indexable by search engines.If unchecked this page will no longer be indexed by search engines.",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="A brief introduction about the company"
                    ),
                ),
                (
                    "contact",
                    wagtail.fields.StreamField(
                        [("contact", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.EmailBlock", (), {}),
                            2: ("wagtail.blocks.TextBlock", (), {}),
                            3: ("wagtail.blocks.URLBlock", (), {}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("phone", 0),
                                        ("whatsapp", 0),
                                        ("email", 1),
                                        ("address", 2),
                                        ("website", 3),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Contact Information",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("block_quote", 2),
                            ("document", 3),
                            ("embed_block", 4),
                            ("faq", 10),
                            ("further_reading", 17),
                            ("gallery", 21),
                            ("heading_block", 23),
                            ("image_block", 20),
                            ("link", 17),
                            ("nav_tab", 27),
                            ("paragraph_block", 28),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.TextBlock", (), {}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "label": "e.g. Mary Berry",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("attribute_name", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"template": "blocks/document_block.html"},
                            ),
                            4: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks",
                                    "icon": "media",
                                    "template": "blocks/embed_block.html",
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Frequently asked questions"},
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            7: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 6), ("answer", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 5), ("item", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use page's listing title.",
                                    "required": False,
                                },
                            ),
                            12: ("wagtail.blocks.PageChooserBlock", (), {}),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 11), ("page", 12)]],
                                {},
                            ),
                            14: ("wagtail.blocks.CharBlock", (), {}),
                            15: ("wagtail.blocks.URLBlock", (), {}),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 14), ("link", 15)]],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.StreamBlock",
                                [[("internal_link", 13), ("external_link", 16)]],
                                {},
                            ),
                            18: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            19: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 18), ("caption", 19), ("attribution", 19)]],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.ListBlock",
                                (20,),
                                {"template": "blocks/gallery_block.html"},
                            ),
                            22: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select a header size"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 6), ("size", 22)]],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "required": True,
                                    "template": "blocks/paragraph_block.html",
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("content", 24)]],
                                {},
                            ),
                            26: ("wagtail.blocks.ListBlock", (25,), {}),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("item", 26)]],
                                {},
                            ),
                            28: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "icon": "pilcrow",
                                    "template": "blocks/paragraph_block.html",
                                },
                            ),
                        },
                        verbose_name="Page body",
                    ),
                ),
                (
                    "faq",
                    wagtail.fields.StreamField(
                        [("faq", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Frequently asked questions"},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            2: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 1), ("answer", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("item", 4)]],
                                {},
                            ),
                        },
                        verbose_name="FAQ Section",
                    ),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("Links", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave blank to use page's listing title.",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.PageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("page", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0), ("item", 4)]],
                                {},
                            ),
                        },
                        verbose_name="Links Section",
                    ),
                ),
                (
                    "amenities",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="partners.amenity"
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose an image you wish to be displayed when this page appears on listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose an image you wish to display when this page appears on social media",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "partnerpage",
                "verbose_name_plural": "partnerpages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="PartnerPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="partners.partnerpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="partnerpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="partners.PartnerPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
