# Generated by Django 5.1.9 on 2025-06-22 15:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_partnerpage_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpage",
            name="ratings",
            field=wagtail.fields.StreamField(
                [("Ratings", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 5 stars?"},
                    ),
                    1: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 4 stars?"},
                    ),
                    2: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 3 stars?"},
                    ),
                    3: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 2 stars?"},
                    ),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 0, "help_text": "How many 1 star?"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("five", 0),
                                ("four", 1),
                                ("three", 2),
                                ("two", 3),
                                ("one", 4),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Ratings",
            ),
        ),
    ]
