# Generated by Django 5.1.9 on 2025-06-22 16:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_partnerpage_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerpage",
            name="destinations",
            field=wagtail.fields.StreamField(
                [("destinations", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Keep it to one word only", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("image", 2), ("page", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("item", 5)]],
                        {},
                    ),
                },
                verbose_name="Destinations where this operator has presence",
            ),
        ),
        migrations.AddField(
            model_name="partnerpage",
            name="info",
            field=wagtail.fields.StreamField(
                [("Info", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "required": True,
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("item", 3)]],
                        {},
                    ),
                },
                verbose_name="Info Section",
            ),
        ),
    ]
