# Generated by Django 6.0.2 on 2026-03-07 07:29

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partnerpage_destinations_partnerpage_info'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.AddField(
            model_name='partnerindexpage',
            name='body',
            field=wagtail.fields.StreamField([('block_quote', 2), ('document', 3), ('embed_block', 4), ('faq', 10), ('further_reading', 17), ('gallery', 21), ('heading_block', 23), ('image_block', 20), ('link', 17), ('nav_tab', 27), ('paragraph_block', 28)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('attribute_name', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'template': 'blocks/document_block.html'}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'template': 'blocks/embed_block.html'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions'}), 6: ('wagtail.blocks.CharBlock', (), {'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('question', 6), ('answer', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('item', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('page', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {}), 15: ('wagtail.blocks.URLBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('link', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('internal_link', 13), ('external_link', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('image', 18), ('caption', 19), ('attribution', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'template': 'blocks/gallery_block.html'}), 22: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('heading_text', 6), ('size', 22)]], {}), 24: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'required': True, 'template': 'blocks/paragraph_block.html'}), 25: ('wagtail.blocks.StructBlock', [[('title', 6), ('content', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('title', 6), ('item', 26)]], {}), 28: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'blocks/paragraph_block.html'})}, verbose_name='Page body'),
        ),
        migrations.AddField(
            model_name='partnerindexpage',
            name='faq',
            field=wagtail.fields.StreamField([('faq', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions'}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 4)]], {})}, verbose_name='FAQ Section'),
        ),
        migrations.AddField(
            model_name='partnerindexpage',
            name='links',
            field=wagtail.fields.StreamField([('Links', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('page', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 6)]], {})}, verbose_name='Links Section'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Name of the icon', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PartnerPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='partners.partnerpage')),
            ],
            options={
                'verbose_name': 'partnerpagegallery',
                'verbose_name_plural': 'partnerpagegalleries',
            },
        ),
    ]
