# Generated by Django 6.0.2 on 2026-08-17 10:20

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_remove_amenity_icon_partnerindexpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerpage',
            name='cities',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='countries',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='daily_departures',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Daily departures'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='num_routes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Routes'),
        ),
        migrations.AddField(
            model_name='partnerpage',
            name='routes',
            field=wagtail.fields.StreamField([('Routes', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('page', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 6)]], {})}, verbose_name='Routes Section'),
        ),
    ]
