# Generated by Django 6.0.2 on 2026-02-22 11:48

import django.core.validators
import django.db.models.deletion
import locations.models
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_stationpage_links'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('icon', models.CharField(help_text='Only name of the icon', max_length=20, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='stationpage',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminales', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='directions',
            field=wagtail.fields.StreamField([('block_quote', 2), ('document', 3), ('embed_block', 4), ('faq', 10), ('further_reading', 17), ('gallery', 21), ('heading_block', 23), ('image_block', 20), ('link', 17), ('nav_tab', 27), ('paragraph_block', 28)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('attribute_name', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'template': 'blocks/document_block.html'}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'template': 'blocks/embed_block.html'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions'}), 6: ('wagtail.blocks.CharBlock', (), {'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('question', 6), ('answer', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('item', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('page', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {}), 15: ('wagtail.blocks.URLBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('link', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('internal_link', 13), ('external_link', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('image', 18), ('caption', 19), ('attribution', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'template': 'blocks/gallery_block.html'}), 22: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('heading_text', 6), ('size', 22)]], {}), 24: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'required': True, 'template': 'blocks/paragraph_block.html'}), 25: ('wagtail.blocks.StructBlock', [[('title', 6), ('content', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('title', 6), ('item', 26)]], {}), 28: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'blocks/paragraph_block.html'})}, verbose_name='Directions (Como llegar?)'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+595 981 123 456'. Up to 17 digits allowed.", regex='^\\+?1?\\d{9,17}$')], verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='ratings',
            field=wagtail.fields.StreamField([('Ratings', 5)], blank=True, block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 5 stars?'}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 4 stars?'}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 3 stars?'}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 2 stars?'}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'How many 1 star?'}), 5: ('wagtail.blocks.StructBlock', [[('five', 0), ('four', 1), ('three', 2), ('two', 3), ('one', 4)]], {})}, verbose_name='Ratings'),
        ),
        migrations.AlterField(
            model_name='stationpage',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('weekday', models.PositiveIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('open_time', models.TimeField(default=locations.models.default_open_time, verbose_name='start')),
                ('close_time', models.TimeField(default=locations.models.default_close_time, verbose_name='end')),
                ('closed', models.BooleanField(default=False, verbose_name='closed')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='locations.stationpage')),
            ],
            options={
                'verbose_name': 'openinghour',
                'verbose_name_plural': 'openinghours',
            },
        ),
        migrations.AddField(
            model_name='stationpage',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='locations.service'),
        ),
        migrations.CreateModel(
            name='StationPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='caption')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='locations.stationpage')),
            ],
            options={
                'verbose_name': 'stationpagegallery',
                'verbose_name_plural': 'stationpagegallery',
            },
        ),
    ]
