# Generated by Django 6.0.2 on 2026-08-23 10:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_service_stationpage_departamento_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationindexpage',
            name='body',
            field=wagtail.fields.StreamField([('block_quote', 2), ('document', 3), ('embed_block', 4), ('faq', 10), ('further_reading', 17), ('gallery', 21), ('heading_block', 23), ('image_block', 20), ('link', 17), ('nav_tab', 27), ('paragraph_block', 28)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('attribute_name', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'template': 'blocks/document_block.html'}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media', 'template': 'blocks/embed_block.html'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions'}), 6: ('wagtail.blocks.CharBlock', (), {'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('question', 6), ('answer', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('item', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('page', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {}), 15: ('wagtail.blocks.URLBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('link', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('internal_link', 13), ('external_link', 16)]], {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('image', 18), ('caption', 19), ('attribution', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'template': 'blocks/gallery_block.html'}), 22: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('heading_text', 6), ('size', 22)]], {}), 24: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'required': True, 'template': 'blocks/paragraph_block.html'}), 25: ('wagtail.blocks.StructBlock', [[('title', 6), ('content', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('title', 6), ('item', 26)]], {}), 28: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'blocks/paragraph_block.html'})}, verbose_name='Page body'),
        ),
        migrations.AddField(
            model_name='stationindexpage',
            name='faq',
            field=wagtail.fields.StreamField([('faq', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions'}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 4)]], {})}, verbose_name='FAQ Section'),
        ),
        migrations.AddField(
            model_name='stationindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='stationindexpage',
            name='links',
            field=wagtail.fields.StreamField([('Links', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('page', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('item', 4)]], {})}, verbose_name='Links Section'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='country',
            field=models.CharField(blank=True, choices=[('ARG', 'Argentina'), ('BOL', 'Bolivia'), ('BRA', 'Brasil'), ('CHL', 'Chile'), ('PGY', 'Paraguay'), ('PER', 'Perú'), ('URU', 'Uruguay')], max_length=20, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='info',
            field=wagtail.fields.StreamField([('Info', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'required': True, 'template': 'blocks/paragraph_block.html'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('item', 3)]], {})}, verbose_name='Info Section'),
        ),
        migrations.AddField(
            model_name='stationpage',
            name='province',
            field=models.CharField(blank=True, choices=[('APY', 'Alto Paraguay'), ('ALP', 'Alto Paraná'), ('ASU', 'Asunción'), ('AMB', 'Amambay'), ('BOQ', 'Boquerón'), ('CGZ', 'Caaguazú'), ('CZP', 'Caazapá'), ('CAN', 'Canindeyú'), ('CNT', 'Central'), ('CON', 'Concepción'), ('COR', 'Cordillera'), ('GUA', 'Guairá'), ('ITA', 'Itapuá'), ('MIS', 'Misiones'), ('NIM', 'Ñeembucú'), ('PAR', 'Paraguarí'), ('PRH', 'Presidente Hayes'), ('SPD', 'San Pedro')], max_length=20, verbose_name='Province'),
        ),
    ]
